import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { Search, ShoppingBag, UserRound, Menu, X, ChevronRight, ArrowRight, Leaf, ShieldCheck, Truck, Heart, Minus, Plus, Trash2, CheckCircle2 } from 'lucide-react';
import './styles.css';
import { categories, products, getProduct } from './lib/products';

const money = n => `₹${n.toLocaleString('en-IN')}`;

function App() {
  const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('po-cart') || '[]'));
  const [menu, setMenu] = useState(false);
  useEffect(() => localStorage.setItem('po-cart', JSON.stringify(cart)), [cart]);
  const add = (p, qty=1) => setCart(c => { const found=c.find(i=>i.id===p.id); return found ? c.map(i=>i.id===p.id?{...i,qty:i.qty+qty}:i) : [...c,{id:p.id,qty}]; });
  const update = (id, qty) => setCart(c => qty<=0?c.filter(i=>i.id!==id):c.map(i=>i.id===id?{...i,qty}:i));
  const cartCount = cart.reduce((s,i)=>s+i.qty,0);
  return <>
    <Announcement />
    <Header count={cartCount} menu={menu} setMenu={setMenu} />
    {menu && <MobileMenu close={()=>setMenu(false)} />}
    <Routes>
      <Route path="/" element={<Home add={add}/>} />
      <Route path="/shop" element={<Shop add={add}/>} />
      <Route path="/category/:category" element={<Shop add={add}/>} />
      <Route path="/product/:id" element={<Product add={add}/>} />
      <Route path="/cart" element={<Cart cart={cart} update={update}/>} />
      <Route path="/checkout" element={<Checkout cart={cart} update={update}/>} />
      <Route path="/about" element={<About/>} />
    </Routes>
    <Footer />
  </>;
}

function Announcement(){ return <div className="announcement">Pure choices. Kinder living. <span>Free shipping on orders above ₹1,499</span></div> }
function Header({count,menu,setMenu}){ return <header className="header"><div className="header-inner"><button className="icon-btn mobile-only" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><Link to="/" className="brand"><span className="brand-mark"><Leaf size={20}/></span><span>pure<span>&</span>organic</span></Link><nav className="desktop-nav"><Link to="/shop">Shop</Link><Link to="/category/wellness">Wellness</Link><Link to="/category/bodycare">Body Care</Link><Link to="/category/home">Eco Home</Link><Link to="/category/gifts">Gifts</Link><Link to="/about">Our Story</Link></nav><div className="header-actions"><button className="icon-btn"><Search/></button><button className="icon-btn"><UserRound/></button><Link className="bag" to="/cart"><ShoppingBag/><span>{count}</span></Link></div></div></header> }
function MobileMenu({close}){ return <div className="mobile-menu"><Link onClick={close} to="/shop">Shop All</Link>{categories.map(c=><Link onClick={close} key={c.id} to={`/category/${c.id}`}>{c.name}</Link>)}<Link onClick={close} to="/about">Our Story</Link></div> }

function Home({add}){ return <main>
  <section className="hero"><div className="hero-copy"><div className="eyebrow">PURE • NATURAL • CONSCIOUS</div><h1>Goodness from<br/><em>nature to home.</em></h1><p>Thoughtfully chosen organic foods, natural body care and earth-friendly essentials for everyday living.</p><div className="hero-actions"><Link className="btn dark" to="/shop">Explore the collection <ArrowRight size={17}/></Link><Link className="text-link" to="/about">Why Pure & Organic <ChevronRight size={16}/></Link></div></div><div className="hero-art"><div className="sun"></div><div className="leaf-art leaf-one">❧</div><div className="leaf-art leaf-two">❧</div><div className="jar"><div className="jar-lid"></div><div className="jar-label">PURE<br/><small>& ORGANIC</small></div></div><div className="hero-stamp">100%<br/><small>CONSCIOUS</small></div></div></section>
  <TrustBar/>
  <section className="section"><SectionHead eyebrow="SHOP BY CATEGORY" title="Simple choices, made better" link="View all"/><div className="category-grid">{categories.map(c=><Link className="category-card" to={`/category/${c.id}`} key={c.id}><div className="category-icon">{c.icon}</div><h3>{c.name}</h3><span>Explore <ArrowRight size={15}/></span></Link>)}</div></section>
  <section className="section soft"><SectionHead eyebrow="CUSTOMER FAVOURITES" title="Made for everyday rituals" link="Shop all"/><ProductGrid list={products.slice(0,4)} add={add}/></section>
  <section className="values"><div><div className="eyebrow">OUR PROMISE</div><h2>Nothing unnecessary.<br/><em>Everything intentional.</em></h2><p>We believe everyday products can be cleaner, kinder and more transparent. Pure & Organic brings together thoughtful choices for your pantry, personal care and home.</p><Link className="btn light" to="/about">Discover our story <ArrowRight size={17}/></Link></div><div className="value-list"><Value icon={<Leaf/>} title="Thoughtfully sourced" text="Ingredients and materials selected with care."/><Value icon={<ShieldCheck/>} title="Clean & transparent" text="Clear product information, without the noise."/><Value icon={<Heart/>} title="Kind to the planet" text="Choices that support a more conscious home."/></div></section>
  <section className="section"><div className="newsletter"><div><div className="eyebrow">THE PURE NOTE</div><h2>Little ways to live well.</h2><p>New arrivals, seasonal favourites and simple ideas for a more natural home.</p></div><div className="subscribe"><input placeholder="Your email address"/><button className="btn dark">Join us</button></div></div></section>
</main> }
function TrustBar(){return <div className="trust"><div><Leaf/><span><b>Natural choices</b><small>Thoughtfully selected</small></span></div><div><ShieldCheck/><span><b>Quality first</b><small>Clear & transparent</small></span></div><div><Truck/><span><b>Easy delivery</b><small>Across India</small></span></div><div><Heart/><span><b>Conscious living</b><small>Better everyday choices</small></span></div></div>}
function Value({icon,title,text}){return <div className="value"><div className="value-icon">{icon}</div><div><h3>{title}</h3><p>{text}</p></div></div>}
function SectionHead({eyebrow,title,link}){return <div className="section-head"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{link&&<Link to="/shop" className="text-link">{link}<ArrowRight size={16}/></Link>}</div>}

function Shop({add}){const {category}=useParams(); const [q,setQ]=useState(''); const filtered=products.filter(p=>(!category||p.category===category)&&p.name.toLowerCase().includes(q.toLowerCase())); const title=category?categories.find(c=>c.id===category)?.name:'All products'; return <main className="shop"><div className="shop-hero"><div className="eyebrow">PURE & ORGANIC</div><h1>{title}</h1><p>Clean, considered products for your pantry, body and home.</p></div><div className="shop-toolbar"><div className="searchbox"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products..."/></div><span>{filtered.length} products</span></div><ProductGrid list={filtered} add={add}/></main>}
function ProductGrid({list,add}){return <div className="product-grid">{list.map(p=><ProductCard key={p.id} p={p} add={add}/>)}</div>}
function ProductCard({p,add}){return <article className="product-card"><Link to={`/product/${p.id}`} className={`product-image ${p.tone}`}><div className="product-shape"></div>{p.badge&&<span className="badge">{p.badge}</span>}</Link><div className="product-info"><div className="product-category">{categories.find(c=>c.id===p.category)?.name}</div><Link to={`/product/${p.id}`}><h3>{p.name}</h3></Link><div className="size">{p.size}</div><div className="price-row"><span className="price">{money(p.price)}</span>{p.oldPrice&&<span className="old-price">{money(p.oldPrice)}</span>}<button className="add-btn" onClick={()=>add(p)}>ADD</button></div></div></article>}

function Product({add}){const {id}=useParams(); const p=getProduct(id); const [qty,setQty]=useState(1); if(!p)return <NotFound/>; return <main className="product-page"><div className={`detail-image ${p.tone}`}><div className="large-shape"></div><span className="badge">{p.badge||'PURE'}</span></div><div className="detail-copy"><div className="eyebrow">{categories.find(c=>c.id===p.category)?.name}</div><h1>{p.name}</h1><div className="detail-price">{money(p.price)} <del>{p.oldPrice?money(p.oldPrice):''}</del></div><p className="detail-size">{p.size} • Tax included</p><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>✓ {t}</span>)}</div><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><b>{qty}</b><button onClick={()=>setQty(qty+1)}><Plus/></button></div><button className="btn dark full" onClick={()=>add(p,qty)}>Add to cart <ShoppingBag size={17}/></button><div className="detail-note"><Truck/> Delivery available across India</div></div></main>}

function Cart({cart,update}){const items=cart.map(i=>({...i,p:getProduct(i.id)}));const subtotal=items.reduce((s,i)=>s+i.p.price*i.qty,0);return <main className="cart-page"><div className="eyebrow">YOUR BAG</div><h1>Your cart</h1>{!items.length?<div className="empty"><ShoppingBag size={40}/><h2>Your bag is waiting.</h2><p>Discover something good for your home.</p><Link className="btn dark" to="/shop">Continue shopping</Link></div>:<div className="cart-layout"><div className="cart-items">{items.map(i=><div className="cart-item" key={i.id}><div className={`cart-thumb ${i.p.tone}`}><div className="product-shape"></div></div><div className="cart-item-main"><Link to={`/product/${i.p.id}`}><h3>{i.p.name}</h3></Link><span>{i.p.size}</span><button className="remove" onClick={()=>update(i.id,0)}><Trash2 size={14}/> Remove</button></div><div className="cart-qty"><button onClick={()=>update(i.id,i.qty-1)}><Minus/></button><b>{i.qty}</b><button onClick={()=>update(i.id,i.qty+1)}><Plus/></button></div><strong>{money(i.p.price*i.qty)}</strong></div>)}</div><aside className="summary"><h2>Order summary</h2><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Shipping</span><b>{subtotal>=1499?'Free':'Calculated at checkout'}</b></div><hr/><div className="total"><span>Total</span><b>{money(subtotal)}</b></div><Link className="btn dark full" to="/checkout">Proceed to checkout <ArrowRight size={17}/></Link><p className="secure"><ShieldCheck size={15}/> Secure checkout</p></aside></div>}</main>}

function Checkout({cart}){const items=cart.map(i=>({...i,p:getProduct(i.id)}));const subtotal=items.reduce((s,i)=>s+i.p.price*i.qty,0);const [status,setStatus]=useState(''); const [form,setForm]=useState({name:'',email:'',phone:'',address:'',city:'',pincode:''}); const change=e=>setForm({...form,[e.target.name]:e.target.value}); const pay=async e=>{e.preventDefault();setStatus('Demo checkout ready — connect the Supabase Edge Function to activate Razorpay.');}; if(!items.length)return <NavigateToCart/>;return <main className="checkout"><div className="eyebrow">CHECKOUT</div><h1>Complete your order</h1><div className="checkout-layout"><form className="checkout-form" onSubmit={pay}><h2>Delivery details</h2><div className="form-grid"><input required name="name" value={form.name} onChange={change} placeholder="Full name"/><input required type="email" name="email" value={form.email} onChange={change} placeholder="Email address"/><input required name="phone" value={form.phone} onChange={change} placeholder="Phone number"/><input required name="pincode" value={form.pincode} onChange={change} placeholder="Pincode"/><input required className="span-2" name="address" value={form.address} onChange={change} placeholder="Address"/><input required name="city" value={form.city} onChange={change} placeholder="City"/><input name="state" placeholder="State"/></div><h2>Payment</h2><div className="payment-choice"><span className="radio active"></span><div><b>Razorpay</b><small>UPI, cards, net banking and more</small></div><span>🔒</span></div><button className="btn dark full" type="submit">Pay {money(subtotal)} <ArrowRight size={17}/></button>{status&&<div className="status"><CheckCircle2/> {status}</div>}</form><aside className="summary"><h2>Your order</h2>{items.map(i=><div className="mini-item" key={i.id}><span>{i.p.name} × {i.qty}</span><b>{money(i.p.price*i.qty)}</b></div>)}<hr/><div className="total"><span>Total</span><b>{money(subtotal)}</b></div></aside></div></main>}
function NavigateToCart(){return <main className="empty"><ShoppingBag/><h2>Your cart is empty.</h2><Link className="btn dark" to="/shop">Shop now</Link></main>}
function About(){return <main className="about"><section className="about-hero"><div className="eyebrow">OUR STORY</div><h1>A quieter, cleaner way<br/><em>to choose everyday.</em></h1><p>Pure & Organic is built around a simple belief: what we bring into our homes should feel good to use, understand and share.</p></section><section className="about-grid"><div><div className="eyebrow">OUR VALUES</div><h2>Less noise.<br/>More intention.</h2></div><div className="about-copy"><p>We curate natural foods, personal care and home essentials with an emphasis on thoughtful sourcing, straightforward information and responsible choices.</p><p>Our goal is not perfection. It is to make better everyday choices easier—one product at a time.</p></div></section></main>}
function NotFound(){return <main className="empty"><h1>Product not found</h1><Link className="btn dark" to="/shop">Back to shop</Link></main>}
function Footer(){return <footer><div className="footer-main"><div><Link className="brand footer-brand" to="/"><span className="brand-mark"><Leaf size={20}/></span><span>pure<span>&</span>organic</span></Link><p>Thoughtful products for a cleaner, kinder everyday life.</p></div><div><h4>Shop</h4><Link to="/shop">All products</Link><Link to="/category/wellness">Wellness</Link><Link to="/category/bodycare">Body Care</Link><Link to="/category/home">Eco Home</Link></div><div><h4>About</h4><Link to="/about">Our story</Link><a href="#">Contact</a><a href="#">Shipping</a><a href="#">Returns</a></div><div><h4>Stay connected</h4><p>Follow our journey toward simpler, more conscious living.</p></div></div><div className="footer-bottom"><span>© 2026 Pure & Organic</span><span>Made with intention in India</span></div></footer>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
